### ISSUE TITLE
Why right click on the link will be deleted?

### ISSUE THREAD

**Issue by ibcLee** [renato-bohler/logossim#25]
when  right click the link, the link will be removed, I did not find the code of the relevant logic

**Comment by renato-bohler** [comment]
This behavior is defined here:

https://github.com/projectstorm/react-diagrams/blob/0deaec246d7fae9d3fc3e8acfaafe3576660f2f8/packages/react-diagrams-defaults/src/link/DefaultLinkSegmentWidget.tsx#L44-L49

**Comment by ibcLee** [comment]
@renato-bohler aha, thanks
