### ISSUE TITLE
Question: Could you please tell me how you are keeping track of changes on your canvas/circuit?

### ISSUE THREAD

**Issue by agarwalishan** [renato-bohler/logossim#44]

**Comment by renato-bohler** [comment]
I'm not tracking changes on the circuit. I only serialize the `react-diagram`'s model whenever I need to know what's in the circuit, which happens only when the user is saving the circuit (or autosaving) and when the user simulation starts the simulation.

**Comment by agarwalishan** [comment]
Okay Thanks
