### ISSUE TITLE
Add an open source license?

### ISSUE THREAD

**Issue by JSv4** [renato-bohler/logossim#45]
Very nicely designed application! I think your UI in particular (without the logic simulations and components) could be its own open source project and quite successful at that. I think this is the best example of a modular, React-compatible visual programming / digraph editor I've found yet. It's based on react-diagrams too, which is a plus as it has so many backers on github. I'd love to use the UI for a very, very different application, but I don't see a license on your repository. If you guys are going the open source route, can you please add one so I know if it's something I can use with my other licenses?

**Comment by renato-bohler** [comment]
Hey there. Thanks for the feedback!

I'm not planning on separating the UI from the rest of the project right now, but that is actually a good idea.

Oh, and I'll probably add a MIT license in the next couple of days... I thought it had a license already :sweat_smile:

**Comment by renato-bohler** [comment]
Done!

**Comment by JSv4** [comment]
Awesome, @renato-bohler! Love that you licensed this under MIT. I am really impressed with not just the implementation but the workflow itself. Very clean and intuitive. I am in the process of working on a tool that needs this kind of visual programming workflow. I don't think I'll be able to use your code for my first release as my architecture is pretty built out already and I need to release sometime this century :-), but would be interested in potentially helping separate out your UI as a separate package for a subsequent release.
