### ISSUE TITLE
Add project setup/installation

### ISSUE THREAD

**Issue by mrbasel** [renato-bohler/logossim#67]
I tried running the project on my local machine, but I couldn't figure out how to properly install it and kept running into errors.

It would be great if you could add a short setup guide in the README.

Thanks.

**Comment by renato-bohler** [comment]
Hey!

Yeah, I should definitely have a section on the README on how to run the project locally.

It should be pretty straight forward though:

1. Have NodeJS installed (I have version `15.11.0` installed, but I'd say 12+ should be fine)
2. Have Yarn installed (I have version `1.22.5` installed here)
3. Clone the project
4. Open the terminal on the project root (`/logossim`)
5. Run `yarn` to install dependencies
6. Run  `yarn start` to start the project. It should automatically open http://localhost:3000 on your browser

If that still does not work, you'll need to share the exact error you're getting so we can investigate further.

**Comment by mrbasel** [comment]
Thank you very much, Its working now.

Awesome project btw.
